[package]
version = "0.1.0"
category = "isaaclab"
readme = "README.md"

title = "Control Policy"
author = "Kevin Murera"
maintainer = "Kevin Murera"
description = "Independent control policy extension"
repository = ""
keywords = ["isaaclab", "control", "policy"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}

[[python.module]]
name = "control_policy"

[isaaclab_settings]
# apt_deps = ["example_package"]
# ros_ws = "path/from/extension_root/to/ros_ws"
